### ISSUE TITLE
Feature detection bug

### ISSUE THREAD

**Issue by zloirock** [es-shims/Symbol.prototype.description#3]
> `typeof desc.get.call(Symbol()) !== 'undefined' || desc.get.call(Symbol()) !== ''`

**Comment by ljharb** [comment]
Can you elaborate more besides just pasting some of the code from https://github.com/es-shims/Symbol.prototype.description/blob/master/polyfill.js#L16?

Some english describing the problem, and a test case, would be most helpful.

**Comment by zloirock** [comment]
This JS example looks for me much more obvious than any English description. It's always `true`.

**Comment by ljharb** [comment]
If it was obvious, the bug would not be there in the first place - an English description always helps.

The first condition is true only when `desc.get.call(Symbol())` returns `undefined`; the second is false only when it returns the empty string.

I think I see what you mean - when it returns `undefined`, the first condition will be true, and when it returns the empty string, the first will still be true. 

Thanks - the only consequence of this is that an environment with a native implementation will be unnecessarily (but correctly) shimmed, and since there's no environments that provide Symbol.prototype.description yet, nobody would be running into this. I'll clean it up shortly.

**Comment by zloirock** [comment]
> and since there's no environments that provide `Symbol.prototype.description` yet

it's available in `core-js` for a long time -)

**Comment by ljharb** [comment]
So the bug is that when someone combines core-js and this shim (which would be a very strange and unsupported thing to do), in that order, it unnecessarily replaces the core-js shim? What issues does this cause?

**Comment by zloirock** [comment]
Yes, `core-js` implementation works as should per specification and will not pass this detection, but it was mentioned just because you wrote that no environments with `Symbol.prototype.description`. I don't think that someone could have any serious problem when this polyfill will replace `core-js` implementation, I found it just when took a look at the code.

**Comment by ljharb** [comment]
Thanks, appreciate the report.
